version: "2"

linters:
  settings:
    cyclop:
      max-complexity: 13
    gocyclo:
      min-complexity: 15
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

  default: all
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - depguard
    - wsl
    - durationcheck
    - wrapcheck
    - varnamelen
    - tagalign
    - tagliatelle
    - nilnil
    - nilerr
    - mnd
    - exhaustruct
    - err113
    - paralleltest
  exclusions:
    rules:
      - linters:
        - dupl
        - errcheck
        - goconst
        - gocyclo
        - testpackage
        path: _test\.go

